const Discord = require('discord.js');
const { prefix } = require('../config.json');

module.exports = {
    name: 'commands',
    execute(client, message, args){
        const embed = new Discord.MessageEmbed()
        .setColor('#7289DA')
        .setTitle('Safe For Work - Commands')
        .addField(prefix + 'help', 'Returns a help module', true)
        .addField(prefix + 'hug', 'Hug a user', true)
        .addField(prefix + 'kiss', 'Kiss a user', true)
        .addField(prefix + 'pat', 'Pat a user', true)
        .addField(prefix + 'slap', 'Slap a user', true)
        .addField(prefix + 'tickle', 'Tickle a user', true)
        .addField(prefix + 'poke', 'Poke a user', true)
        .addField(prefix + 'cuddle', 'Cuddle a user', true)
        .addField(prefix + 'feed', 'Feed a user', true)
        .addField(prefix + 'cat', 'Returns a cat image/gif', true)
        .addField(prefix + 'dog', 'Returns a dog image/gif', true)
        .addField(prefix + 'goose', 'Returns a goose image', true)
        .addField(prefix + 'smug', 'Returns a smug image/gif', true)
        .addField(prefix + 'baka', 'Returns a baka image/gif', true)
        .addField(prefix + 'neko', 'Returns a neko image', true)
        .addField(prefix + 'nekogif', 'Returns a neko gif', true)
        .addField(prefix + 'lizard', 'Returns a lizard image/gif', true)
        .addField(prefix + 'foxgirl', 'Returns a foxgirl image/gif', true)
        .addField(prefix + 'holo', 'Returns a holo image/gif', true)
        .addField(prefix + 'wallpaper', 'Returns a wallpaper', true)
        .addField(prefix + 'gecg', 'Returns a genetically genetically engineered catgirl image', true)
        .addField(prefix + 'avatar', 'Returns an anime avatar', true)
        .addField(prefix + 'waifu', 'Returns a waifu image/gif', true)
        .addField(prefix + 'owofy', 'Returns a owofied version of your text', true)
        .addField(prefix + 'cattext', 'Returns a cattext emoji', true)
        const embed2 = new Discord.MessageEmbed()
        .setColor('#7289DA')
        .addField(prefix + 'fact', 'Returns a random fact', true)
        .addField(prefix + 'spoiler', 'Returns a message with a unique spoiler for ever text letter', true)
        .addField(prefix + 'why', 'Returns a random question', true)
        const embed3 = new Discord.MessageEmbed()
        .setColor('#7289DA')
        .setTitle('Not Safe For Work - Commands')
        .addField(prefix + 'pussy', 'Returns a pussy image/gif', true)
        .addField(prefix + 'lesbian', 'Returns a lesbian image/gif', true)
        .addField(prefix + 'cumsluts', 'Returns a cumsluts image/gif', true)
        .addField(prefix + 'boobs', 'Returns a boobs image/gif', true)
        .addField(prefix + 'blowjob', 'Returns a blowjob image/gif', true)
        .addField(prefix + 'anal', 'Returns a anal image/gif', true)
        .addField(prefix + 'trap', 'Returns a trap image/gif', true)
        .addField(prefix + 'tits', 'Returns a tits image/gif', true)
        .addField(prefix + 'spank', 'Returns a spank image/gif', true)
        .addField(prefix + 'cumart', 'Returns a cumart image/gif', true)
        .addField(prefix + 'femdom', 'Returns a femdom image/gif', true)
        .addField(prefix + 'yuri', 'Returns a yuri image/gif', true)
        .addField(prefix + 'nsfwavatar', 'Returns an nsfw avatar', true)
        .addField(prefix + 'hentaigif', 'Returns a hentai gif', true)
        .addField(prefix + 'hentai', 'Returns a hentai image', true)
        .addField(prefix + 'nsfwnekogif', 'Returns a nsfw neko gif', true)
        .addField(prefix + 'nsfwneko', 'Returns a nsfw neko image', true)
        .addField(prefix + 'kuni', 'Returns a kuni image/gif', true)
        .addField(prefix + 'girlsolo', 'Returns a girlsolo image', true)
        .addField(prefix + 'girlsologif', 'Returns a girlsolo gif', true)
        .addField(prefix + 'pussywank', 'Returns a pussywank gif', true)
        .addField(prefix + 'pussyart', 'Returns a pussyart image/gif', true)
        .addField(prefix + 'kitsune', 'Returns a kitsune image/gif', true)
        .addField(prefix + 'futanari', 'Returns a futanari image/gif', true)
        .addField(prefix + 'keta', 'Returns a keta image/gif', true)
        const embed4 = new Discord.MessageEmbed()
        .setColor('#7289DA')
        .addField(prefix + 'gasm', 'Returns a gasm image', true)
        .addField(prefix + 'feetgif', 'Returns a feet gif', true)
        .addField(prefix + 'feet', 'Returns a feet image', true)
        message.channel.send(embed);
        message.channel.send(embed2);
        message.channel.send(embed3);
        message.channel.send(embed4);
    }
}
