const Discord = require('discord.js');
const { prefix } = require('../config.json');

module.exports = {
    name: 'commands',
    execute(client, message, args){
        const embed = new Discord.MessageEmbed()
        .setColor('#7289DA')
        .setTitle('Safe For Work - Commands')
        .addField(prefix + 'help', 'Returns a help module')
        .addField(prefix + 'hug', 'Hug a user')
        .addField(prefix + 'kiss', 'Kiss a user')
        .addField(prefix + 'pat', 'Pat a user')
        .addField(prefix + 'slap', 'Slap a user')
        .addField(prefix + 'tickle', 'Tickle a user')
        .addField(prefix + 'poke', 'Poke a user')
        .addField(prefix + 'cuddle', 'Cuddle a user')
        .addField(prefix + 'feed', 'Feed a user')
        .addField(prefix + 'cat', 'Returns a cat image/gif')
        .addField(prefix + 'dog', 'Returns a dog image/gif')
        .addField(prefix + 'goose', 'Returns a goose image')
        .addField(prefix + 'smug', 'Returns a smug image/gif')
        .addField(prefix + 'baka', 'Returns a baka image/gif')
        .addField(prefix + 'neko', 'Returns a neko image')
        .addField(prefix + 'nekogif', 'Returns a neko gif')
        .addField(prefix + 'lizard', 'Returns a lizard image/gif')
        .addField(prefix + 'foxgirl', 'Returns a foxgirl image/gif')
        .addField(prefix + 'holo', 'Returns a holo image/gif')
        .addField(prefix + 'wallpaper', 'Returns a wallpaper')
        .addField(prefix + 'gecg', 'Returns a genetically genetically engineered catgirl image')
        .addField(prefix + 'avatar', 'Returns an anime avatar')
        .addField(prefix + 'waifu', 'Returns a waifu image/gif')
        .addField(prefix + 'owofy', 'Returns a owofied version of your text')
        .addField(prefix + 'cattext', 'Returns a cattext emoji')
        .addField(prefix + 'fact', 'Returns a random fact')
        .addField(prefix + 'spoiler', 'Returns a message with a unique spoiler for ever text letter')
        .addField(prefix + 'why', 'Returns a random question')
        const embed2 = new Discord.MessageEmbed()
        .setColor('#7289DA')
        .addField(prefix + 'fact', 'Returns a random fact')
        .addField(prefix + 'spoiler', 'Returns a message with a unique spoiler for ever text letter')
        .addField(prefix + 'why', 'Returns a random question')
        const embed3 = new Discord.MessageEmbed()
        .setColor('#7289DA')
        .setTitle('Not Safe For Work - Commands')
        .addField(prefix + 'pussy', 'Returns a pussy image/gif')
        .addField(prefix + 'lesbian', 'Returns a lesbian image/gif')
        .addField(prefix + 'cumsluts', 'Returns a cumsluts image/gif')
        .addField(prefix + 'boobs', 'Returns a boobs image/gif')
        .addField(prefix + 'blowjob', 'Returns a blowjob image/gif')
        .addField(prefix + 'anal', 'Returns a anal image/gif')
        .addField(prefix + 'trap', 'Returns a trap image/gif')
        .addField(prefix + 'tits', 'Returns a tits image/gif')
        .addField(prefix + 'spank', 'Returns a spank image/gif')
        .addField(prefix + 'cumart', 'Returns a cumart image/gif')
        .addField(prefix + 'femdom', 'Returns a femdom image/gif')
        .addField(prefix + 'yuri', 'Returns a yuri image/gif')
        .addField(prefix + 'nsfwavatar', 'Returns an nsfw avatar')
        .addField(prefix + 'hentaigif', 'Returns a hentai gif')
        .addField(prefix + 'hentai', 'Returns a hentai image')
        .addField(prefix + 'nsfwnekogif', 'Returns a nsfw neko gif')
        .addField(prefix + 'nsfwneko', 'Returns a nsfw neko image')
        .addField(prefix + 'kuni', 'Returns a kuni image/gif')
        .addField(prefix + 'girlsolo', 'Returns a girlsolo image')
        .addField(prefix + 'girlsologif', 'Returns a girlsolo gif')
        .addField(prefix + 'pussywank', 'Returns a pussywank gif')
        .addField(prefix + 'pussyart', 'Returns a pussyart image/gif')
        .addField(prefix + 'kitsune', 'Returns a kitsune image/gif')
        .addField(prefix + 'futanari', 'Returns a futanari image/gif')
        .addField(prefix + 'keta', 'Returns a keta image/gif')
        const embed4 = new Discord.MessageEmbed()
        .setColor('#7289DA')
        .addField(prefix + 'gasm', 'Returns a gasm image')
        .addField(prefix + 'feetgif', 'Returns a feet gif')
        .addField(prefix + 'feet', 'Returns a feet image')
        message.channel.send(embed);
        message.channel.send(embed2);
        message.channel.send(embed3);
        message.channel.send(embed4);
    }
}